<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Content\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Evergine.Common" Version="2026.5.26.8" />
		<PackageReference Include="Evergine.DirectX11" Version="2026.5.26.8" />
		<PackageReference Include="Evergine.DirectX12" Version="2026.5.26.8" />
		<PackageReference Include="Evergine.Mathematics" Version="2026.5.26.8" />
		<PackageReference Include="Evergine.OpenGL" Version="2026.5.26.8" />
		<PackageReference Include="Evergine.Forms" Version="2026.5.26.8" />
		<PackageReference Include="Evergine.Vulkan" Version="2026.5.26.8" />
		<PackageReference Include="Evergine.WebGPU" Version="2026.5.26.8" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
